/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Class.Kitaplar;
import javax.swing.JOptionPane;

/**
 *
 * @author Kirito
 */
public class Kitap_Ekle extends javax.swing.JPanel {

    /**
     * Creates new form Kitap_Ekle
     */
    public Kitap_Ekle() {
        initComponents();
    }
    Kitaplar kitap= new Kitaplar();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tb_ISBN = new javax.swing.JTextField();
        tb_ad = new javax.swing.JTextField();
        tb_sayfa = new javax.swing.JTextField();
        tb_tur = new javax.swing.JTextField();
        tb_yayinevi = new javax.swing.JTextField();
        tb_yazar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_ekle = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(739, 555));

        jLabel1.setText("ISBN No");

        jLabel2.setText("Kitap Adı");

        jLabel3.setText("Kitap Sayfası");

        jLabel4.setText("Kitap Türü");

        jLabel5.setText("Kitap Yayınevi");

        jLabel6.setText("Kitap Yazar Adı");

        btn_ekle.setText("Ekle");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tb_tur, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(tb_yayinevi)
                            .addComponent(tb_ad)
                            .addComponent(tb_sayfa)
                            .addComponent(tb_yazar)
                            .addComponent(tb_ISBN)))
                    .addComponent(btn_ekle))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_sayfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_tur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_yayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_yazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btn_ekle)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
         
        try
        {
            kitap.setISBN(tb_ISBN.getText());
            kitap.setK_ad(tb_ad.getText().toUpperCase());
            kitap.setK_sayfa(tb_sayfa.getText());
            kitap.setK_tur(tb_tur.getText().toUpperCase());
            kitap.setK_yayinevi(tb_yayinevi.getText().toUpperCase());
            kitap.setK_yazar(tb_yazar.getText().toUpperCase());
        
        if(tb_ISBN.getText().equals("")||tb_sayfa.getText().equals("")||tb_tur.getText().equals("")||tb_yayinevi.getText().equals("")||tb_yazar.getText().equals("")|| tb_ad.getText().equals(""))
        {
            throw new Exception("Boşdeğer Giremzsiniz");
        }
        else if(tb_ISBN.getDocument().getLength()!=13)
            throw new Exception("ISBN numaranız 13 karakter den az veya fazla olamaz");
        
        else if(tb_sayfa.getDocument().getLength()>5)
            throw new Exception("Sayfa numaranız 5 karakter den büyük olamaz");
        
        else if(tb_yayinevi.getDocument().getLength()>50)
            throw new Exception("Yayınevinin adı 50 karakter den büyük olamaz");
                
        else
        {
            kitap.Kitap_Ekle(kitap.getISBN(),kitap.getK_ad(),kitap.getK_sayfa(),kitap.getK_tur(),kitap.getK_yayinevi(),kitap.getK_yazar());
        }
        
        }
        catch(Exception h)
        {
            JOptionPane.showMessageDialog(null,h.getMessage());
        }
    }//GEN-LAST:event_btn_ekleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tb_ISBN;
    private javax.swing.JTextField tb_ad;
    private javax.swing.JTextField tb_sayfa;
    private javax.swing.JTextField tb_tur;
    private javax.swing.JTextField tb_yayinevi;
    private javax.swing.JTextField tb_yazar;
    // End of variables declaration//GEN-END:variables
}
