/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author Kirito
 */
public class MainFrame extends javax.swing.JFrame {

    Ogrenci_Ekle ogr_ekle;
    Kitap_Ekle kitap_ekle;
    Kitap_Kirala kitap_kirala;
    Ogrenci_Islem ogr_islem;
    Kitap_Islem kitap_islem;
    Kitap_Kimde kitap_kimde;
    GridBagLayout layout = new GridBagLayout();
    public MainFrame() {
        initComponents();
        ogr_ekle = new Ogrenci_Ekle();
        kitap_ekle = new Kitap_Ekle();
        kitap_kirala = new Kitap_Kirala();
        ogr_islem = new Ogrenci_Islem();
        kitap_islem =new Kitap_Islem();
        kitap_kimde = new Kitap_Kimde();
        MainPanel.setLayout(layout);
        GridBagConstraints gbc = new GridBagConstraints();
       /* gbc.gridx=0;
        gbc.gridy=0;*/
        MainPanel.add(ogr_ekle,gbc);
        MainPanel.add(kitap_ekle,gbc);
        MainPanel.add(kitap_kirala,gbc);
        MainPanel.add(ogr_islem,gbc);
        MainPanel.add(kitap_islem,gbc);
        MainPanel.add(kitap_kimde,gbc);
        ogr_ekle.setVisible(false);
        kitap_ekle.setVisible(false);
        kitap_kirala.setVisible(false);
        ogr_islem.setVisible(false);
        kitap_islem.setVisible(false); 
        kitap_kimde.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_kitap_islem = new javax.swing.JButton();
        btn_ogr_islem = new javax.swing.JButton();
        btn_kirala = new javax.swing.JButton();
        btn_kitap_ekle = new javax.swing.JButton();
        btn_ogr_ekle = new javax.swing.JButton();
        btn_kitap_nerde = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(860, 567));
        setMinimumSize(new java.awt.Dimension(860, 567));

        MainPanel.setPreferredSize(new java.awt.Dimension(739, 555));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_kitap_islem.setText("Kitap İşlem");
        btn_kitap_islem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kitap_islemActionPerformed(evt);
            }
        });

        btn_ogr_islem.setText("Öğrenci İşlem");
        btn_ogr_islem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ogr_islemActionPerformed(evt);
            }
        });

        btn_kirala.setText("Kitap Kirala");
        btn_kirala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kiralaActionPerformed(evt);
            }
        });

        btn_kitap_ekle.setText("Kitap Ekle");
        btn_kitap_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kitap_ekleActionPerformed(evt);
            }
        });

        btn_ogr_ekle.setText("Öğrenci Ekle");
        btn_ogr_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ogr_ekleActionPerformed(evt);
            }
        });

        btn_kitap_nerde.setText("Kitap Kimde");
        btn_kitap_nerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kitap_nerdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_ogr_islem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_kitap_islem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_kirala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_kitap_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ogr_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_kitap_nerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_ogr_ekle)
                .addGap(7, 7, 7)
                .addComponent(btn_ogr_islem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kitap_ekle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kitap_islem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kirala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kitap_nerde)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kitap_islemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kitap_islemActionPerformed
        ogr_ekle.setVisible(false);
        kitap_ekle.setVisible(false);
        kitap_kirala.setVisible(false);
        ogr_islem.setVisible(false);
        kitap_islem.setVisible(true);
        kitap_kimde.setVisible(false);
    }//GEN-LAST:event_btn_kitap_islemActionPerformed

    private void btn_ogr_islemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ogr_islemActionPerformed
        ogr_ekle.setVisible(false);
        kitap_ekle.setVisible(false);
        kitap_kirala.setVisible(false);
        ogr_islem.setVisible(true);
        kitap_islem.setVisible(false);
        kitap_kimde.setVisible(false);
    }//GEN-LAST:event_btn_ogr_islemActionPerformed

    private void btn_kiralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kiralaActionPerformed
        ogr_ekle.setVisible(false);
        kitap_ekle.setVisible(false);
        kitap_kirala.setVisible(true);
        ogr_islem.setVisible(false);
        kitap_islem.setVisible(false);
        kitap_kimde.setVisible(false);
    }//GEN-LAST:event_btn_kiralaActionPerformed

    private void btn_kitap_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kitap_ekleActionPerformed
        ogr_ekle.setVisible(false);
        kitap_ekle.setVisible(true);
        kitap_kirala.setVisible(false);
        ogr_islem.setVisible(false);
        kitap_islem.setVisible(false);
        kitap_kimde.setVisible(false);
    }//GEN-LAST:event_btn_kitap_ekleActionPerformed

    private void btn_ogr_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ogr_ekleActionPerformed
        ogr_ekle.setVisible(true);
        kitap_ekle.setVisible(false);
        kitap_kirala.setVisible(false);
        ogr_islem.setVisible(false);
        kitap_islem.setVisible(false);
        kitap_kimde.setVisible(false);
    }//GEN-LAST:event_btn_ogr_ekleActionPerformed

    private void btn_kitap_nerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kitap_nerdeActionPerformed
        ogr_ekle.setVisible(false);
        kitap_ekle.setVisible(false);
        kitap_kirala.setVisible(false);
        ogr_islem.setVisible(false);
        kitap_islem.setVisible(false); 
        kitap_kimde.setVisible(true);                                       
    }//GEN-LAST:event_btn_kitap_nerdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btn_kirala;
    private javax.swing.JButton btn_kitap_ekle;
    private javax.swing.JButton btn_kitap_islem;
    private javax.swing.JButton btn_kitap_nerde;
    private javax.swing.JButton btn_ogr_ekle;
    private javax.swing.JButton btn_ogr_islem;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
